---
framework: jasmine
preMerge:
  pattern:
    - "spec/**/*.js"
postMerge:
  pattern:
    - "spec/**/*.js"
preRun: 
  command: 
    - npm ci  
smartRun: true
postRun:
  command: 
    - echo 'Done Testing'
